# Site settings
title: "rhapsodixx"
email: "panji.gautama@gmail.com"
description: "pragmatic programmer stash"
url: "http://panjigautama.github.io"
baseurl: "http://panjigautama.github.io"
twitter_username: panji_g
github_username: panjigautama

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]